spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: daniil801
    driverClassname: org.postgresql.Driver

  rabbitmq:
    port: 5672
    host: 'localhost'
    username: user
    password: password

server:
  port: 8082

logging:
  level:
    root: info
