### all cats

GET http://localhost:8088/cats
Accept: application/json

### cats by name

GET http://localhost:8088/cats/cat?name=John
Accept: application/json

### owner by name

GET http://localhost:8088/cats/cat?name=Ringo
Accept: application/json

### all cats by color

GET http://localhost:8088/cats/filter?color=black
Accept: application/json

### all owners

GET http://localhost:8088/owners
Accept: application/json

### owner by name

GET http://localhost:8088/owners/owner?name=Elvis Presley
Accept: application/json

### owner by name

GET http://localhost:8088/owners/49
Accept: application/json