spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: daniil801
    driverClassname: org.postgresql.Driver

logging:
  level:
    root: info
server:
  port: 8088