# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: daniil801
      POSTGRES_DB: postgres
    ports:
      - 15432:5432

  rabitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 15672:15672
      - 5672:5672