# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: daniil801
      POSTGRES_DB: postgres
    ports:
      - 15432:5432